sparsemat/sprs

- src/errors.rs
- src/sparse/binop.rs
- src/sparse/compressed.rs
- src/sparse/construct.rs
- src/sparse/csmat.rs
- src/sparse/mod.rs
- src/sparse/prod.rs
- src/test_data.rs
Add a trait to represent types that can be borrowed as a CsMatView, and use it as a bound for most algorithms.
> Matrix traits

- Cargo.toml
- README.rst
- src/lib.rs
- src/sparse/binop.rs
- src/sparse/compressed.rs
- src/sparse/construct.rs
- src/sparse/csmat.rs
- src/sparse/linalg/cholesky.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/prod.rs
- src/sparse/symmetric.rs
- src/sparse/triplet.rs
- src/sparse/vec.rs
Most impls had an unneeded Copy bound, now only the methods really requiring it are marked.
Also, where convenient, Copy has been replaced by Clone.
> Remove unnecessary copy bounds

- .gitignore
- README.rst
- src/sparse/csmat.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/symmetric.rs
- src/sparse/vec.rs
Add indexing capabilities for sparse matrices and sparse vectors, allowing one to modify non-zero values. Due to the sparse compression, indexing is not in constant time (logarithmic).
Fixes #62.
> Mutable views for sparse matrices and vectors

- README.rst
- src/errors.rs
- src/lib.rs
- src/sparse/binop.rs
- src/sparse/csmat.rs
- src/sparse/permutation.rs
- src/sparse/prod.rs
- src/sparse/vec.rs
Add `map()`, `map_inplace()` to apply a function to all non-zero elements of a sparse matrix or vector.
Expose the `csmat_binop` and `csvec_binop` functions, which allow applying a function to corresponding non-zero elements of two sparse matrices/vectors.
Fixes #59. For the time being, function application with 3 matrices won't be supported, as it can be emulated by repeated applications of e.g. `csmat_binop`. This has the downside of requiring an extra allocation, but support for function application with 3 matrices would be complicated.
> Per non-zero elements  functions

- src/sparse/csmat.rs
- src/sparse/vec.rs
This enables constant time access to elements of matrices, once the NnzIndex has been computed.
Fixes #63.
> Implement Index trait with NnzIndex as argument

- src/sparse/binop.rs
- src/sparse/construct.rs
- src/sparse/csmat.rs
- src/sparse/linalg/cholesky.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/prod.rs
- src/sparse/symmetric.rs
- src/sparse/to_dense.rs
The old behaviour can be obtained by chaining a call to `enumerate()`.
Fixes #73.
> `outer_iterator()` no longer returns the dimension index

- README.rst
- src/lib.rs
- src/sparse/binop.rs
- src/sparse/compressed.rs
- src/sparse/construct.rs
- src/sparse/csmat.rs
- src/sparse/linalg/cholesky.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/mod.rs
- src/sparse/prod.rs
- src/sparse/symmetric.rs
- src/sparse/to_dense.rs
- src/sparse/triplet.rs
- src/sparse/vec.rs
- src/test_data.rs
Refactor `CsMat` and `CsVec` constructors to allow more ergonomic interaction.
Constructors yielding owned matrices no longer require a storage argument, instead different functions are provided for the csr/csc cases, with csr being the default. Owning constructors are now more tolerant to structure errors (they will sort indices if necessary) but will panick on unrecoverable structure errors (eg out of bounds indices).
Shape arguments are now passed using a tuple.
Fixes #81.
> Constructor refactor

- .gitignore
- .travis.yml
- Cargo.toml
- README.rst
- sprs-ldl/Cargo.toml
- sprs-ldl/LICENSE-LGPL
- sprs-ldl/README.rst
- sprs-ldl/src/lib.rs
- src/sparse/linalg/cholesky.rs
- src/sparse/linalg/mod.rs
Since the cholesky factorization code is under LGPL, it's easier to move it to its own crate.
Fixes #79.
> Move cholesky factorization to a separate crate.

- Guidelines.rst
- README.rst
- src/errors.rs
- src/sparse/binop.rs
- src/sparse/construct.rs
- src/sparse/csmat.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/prod.rs
- src/sparse/to_dense.rs
- src/sparse/vec.rs
Remove error codes that corresponded to programming errors. Only error cases left are:
- unsorted indices, since it will be possible to use this error in the future to create a sparse matrix with unsorted indices, which is functional though less performant.
- singular matrices in linear algebra, since this leaves the caller the opportunity to add some regularization.
The errors removed should be plain bugs when they happen (eg dimension mismatch, out of bounds, ...).
> Error policy

- sprs-ldl/src/lib.rs
- src/lib.rs
- src/sparse/construct.rs
- src/sparse/triplet.rs
- src/sparse/vec.rs
Most functionality is now available either directly (eg `sprs::CsMat`) or with one module indirection (eg `sprs::stack::DStack`).
Fixes #71
> Refactor API to expose shorter paths

- README.rst
- src/sparse/csmat.rs
Add the `fn insert(&mut self, row, col, val)` method to enable inserting a non-zero in a `CsMatOwned`.
While this is an inefficent operation in the general case, it is efficient to build a matrix if the elements are supplied in the appropriate order (ie row order for a CSR matrix, col order for a CSC matrix).
Fixes #96 #57
> Csmat insertion

- README.rst
- src/sparse/csmat.rs
- src/sparse/vec.rs
Enables changing the non-zero values of a sparse matrix or vector. The non-zero strcuture cannot be changed by this mean though.
> Mutable iteration for sparse matrices and vectors

- src/lib.rs
- src/sparse/binop.rs
- src/sparse/compressed.rs
- src/sparse/csmat.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/mod.rs
- src/sparse/prod.rs
- src/sparse/triplet.rs
- src/sparse/vec.rs
Rework the module hierarchy to avoid relying on unsafe calls inside the library.
Fixes #98.
> Get rid of unsafe usage

- Cargo.toml
- examples/heat.rs
- src/lib.rs
- src/sparse/binop.rs
- src/sparse/compressed.rs
- src/sparse/construct.rs
- src/sparse/csmat.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/mod.rs
- src/sparse/prod.rs
- src/sparse/symmetric.rs
- src/sparse/to_dense.rs
- src/sparse/triplet.rs
- src/sparse/vec.rs
- src/test_data.rs
Better documentation after the indexing refactor. Now each of the main types (`CsMat`, `TriMat`, `CsVec`) have dedicated documentations. Still a lot to document better but that's a step forward :)
> Documentation improvements

- src/array_backend.rs
- src/lib.rs
- src/sparse/csmat.rs
- src/sparse/mod.rs
- src/sparse/vec.rs
This avoids unnecessary heap allocations.
> use a fixed size array for storing indptr in CsMatVecView

- changelog.rst
- sprs-ldl/src/lib.rs
- src/sparse/permutation.rs
- suitesparse_bindings/sprs_suitesparse_ldl/src/lib.rs
This means less disparity between the identity case and the rest. Now
an identity permutation cannot be used to permute any vector/matrix, but
only those of matching dimension.
Fixes #113.
> Permutation knows its dimention

- src/sparse/vec.rs
This is the first tiny step towards #118.
[alga's `ClosedAdd` trait](https://docs.rs/alga/0.5.2/alga/general/trait.ClosedAdd.html) requires addition by value. These implementations merely delegate to the by-reference implementation. I imagine that there is some space for optimization here later on, if you take ownership of the operands.
The same considerations apply for the other operators, too. I'd be happy to apply the procedure to all of them (could be done in this PR), but I would like to get feedback on this approach first.
> Add vectors by value

- src/sparse/binop.rs
- src/sparse/prod.rs
- src/sparse/vec.rs
See the discussion in #118 for motivation.
~~`Zero` from num-traits has not been implemented yet~~
Also left out was the multiplication of that vector to a matrix from the left. It is more involved, as the left vector is treated like a matrix. A possible solution would be to extend the universal zero concept to matrices.
For now, the above step seems out-of-scope for this PR.
**EDIT:** changed my mind to include the `Zero` trait impl.
> Introduce a zero-sized vector as a "universal zero"

- Cargo.toml
- benches/suite.rs
- src/lib.rs
- src/sparse/mod.rs
- src/sparse/vec.rs
So far for now. I added alga as an optional dependency that is part of the default features. The implementation so far only covers the algebraic structure up to an additive group. It was necessary to implement the negation operator for vectors as well.
Note that this is based on #120.
> Alga integration: additive group for sparse vectors

- .travis.yml
The travis CI build used to silently fail because of this. Having all tests run properly has highlighted the missing dependency.
> install suitesparse in travis CI

- Cargo.toml
Using the old ndarray dependency conflicts with the most recent version.
Upgrade seems straightforward. All tests pass.
> change ndarray version from 0.10.0 to 0.11.2

- .travis_rustfmt
- Guidelines.rst
- sprs-ldl/src/lib.rs
- src/sparse/construct.rs
- src/sparse/csmat.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/prod.rs
- src/sparse/symmetric.rs
- src/sparse/triplet.rs
- src/sparse/vec.rs
[Rustfmt 1.0](https://blog.rust-lang.org/2018/12/17/Rust-2018-dev-tools.html#rustfmt)
Now that Rustfmt is 1.0, this should be the last regular update required to keep up with Rust versions for a while (update may be required for the eventual Rustfmt 2.0 release expected "some time in late 2019"). Rustmft will continue to add new features, but they will be featured gated for all Rustfmt 1.x versions.
> update to rustfmt 1.0 (Rust 1.31)

- src/sparse/csmat.rs
- src/sparse/vec.rs
The obvious use case is when one only wants to keep some internal storage of a vector / matrix object (e.g. non-zero values stored in `data`) and doesn't need the object itself any more.
This also makes vector / matrix transformation more flexible. E.g. one might wants to map inner indices with some bijective function, and the resulting indices could go beyond the original dimension, which would cause `modify` to panic. With `into_raw_storage`, one can pull out the guts of a matrix / vector object, perform arbitrary transformations while avoiding memory copying / allocation if possible, and create a new object using these old storage objects when they are done.
> Support recycling internal containers of vectors & matrices

- Cargo.toml
> expand ndarray version req: work with 0.11.x and 0.12.x. Fixes #142

- src/lib.rs
- src/sparse/construct.rs
- src/sparse/csmat.rs
Would have done the same for `csr_from_dense` and `csc_from_dense` if they were inside the `impl<N, I: SpIndex> CsMatBase<N, I, Vec<I>, Vec<I>, Vec<N>>` block.
> Make construction functions more generic

- src/io/mod.rs
- src/sparse/binop.rs
- src/sparse/construct.rs
- src/sparse/csmat.rs
- src/sparse/permutation.rs
- src/sparse/triplet.rs
- src/sparse/triplet_iter.rs
- src/sparse/vec.rs
- src/stack.rs
Fixing the rest would require changing the current public interface (mostly passing refs instead of values when the latter is unnecessary), so leaving them as is for now.
> Fix some `cargo clippy` warnings

- src/sparse/vec.rs
Previous implementation was leveraging the same logic as the csvec sum,
but this meant that it was visiting the union of nnz states, then
filtering the ones that didn't match. This new implementation inspired
by @tomtung's implementation in #151 is more straightforward and faster.
Results with the small benchmark program by @tomtung:
old version:
```
CsVecBase::dot  6783668708ns
csvec_dot       2281289626ns
CsVecBase::dot  6730220391ns
csvec_dot       2314367501ns
CsVecBase::dot  7211901147ns
csvec_dot       2668089989ns
CsVecBase::dot  2016792998ns
csvec_dot       698307619ns
CsVecBase::dot  3474910028ns
csvec_dot       1231625617ns
CsVecBase::dot  1608800699ns
csvec_dot       594631255ns
CsVecBase::dot  5704293971ns
csvec_dot       2099393986ns
CsVecBase::dot  635824615ns
csvec_dot …
```
> faster implementation of sparse/sparse dot product

- src/sparse/triplet_iter.rs
this line is giving the following warning on the nightly compiler. This patch fixes the warning:
```
warning[E0502]: cannot borrow `indptr` as immutable because it is also borrowed as mutable
--> src/sparse/triplet_iter.rs:122:26
|
122 |             indptr[i] += indptr[i - 1];
|             -------------^^^^^^-------
|             |            |
|             |            immutable borrow occurs here
|             mutable borrow occurs here
|             mutable borrow later used here
|
= warning: this error has been downgraded to a warning for backwards compatibility with previous releases
= warning: this represents potential undefined behavior in your code and this warning will become a hard error in the future
```
> fix borrow warning on nightly

- Cargo.toml
- changelog.rst
- sprs-ldl/Cargo.toml
Aside from new features, this version fixes the warning reported by the transition mode of the borrow checker (see https://github.com/rust-lang/rust/issues/60680). This will enable dependent crates to upgrade and be able to continue building once the transition is over.
> sprs to version 0.6.5, sprs-ldl to version 0.4.1

- src/sparse/binop.rs
- src/sparse/compressed.rs
- src/sparse/construct.rs
- src/sparse/csmat.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/mod.rs
- src/sparse/prod.rs
- src/sparse/symmetric.rs
- src/sparse/to_dense.rs
- src/sparse/vec.rs
(Not pushing directly to main branch given it's a rather large diff.)
This diff adds support to set different types for `indptr` & `indices` in `CsMatBase`, which are currently assumed to have the same type. This can be overly restrictive in some cases: even if the indices are small enough to fit into small integer type, the total number of non-zero entries can still cause overflow.
For example, one might want to use `u32` instead of `usize` for indexing to save space. Say each row has 1000 non-zero elements on average, the total number of elements would overflow `u32` with less than 5MM rows.
Since this diff sets the type for `indptr` to be the same as `indices` by default, this shouldn't break most 3rd party dependent code.
> Support having different types for indptr & indices in CsMatBase

- src/indexing.rs
- src/sparse/binop.rs
- src/sparse/csmat.rs
- src/sparse/permutation.rs
- src/sparse/triplet.rs
- src/sparse/vec.rs
(Not pushing directly to master branch since this diff has performance implications.)
Got bitten by this issue recently (see https://github.com/tomtung/parabel-rs/commit/597a9f2c87a9ac10c33ca31689d60e26d11d6d15), so I think maybe it better to panic even in release mode if arithmatic overflow happens, while providing the option of unchecked casting explicitly.
I think we can look at existing usage in the code base, and figure out where it's safe to do unchecked casts for better performance?
> Make casting from & to SpIndex panic if it overflows

- src/errors.rs
- src/indexing.rs
- src/sparse/csmat.rs
- src/sparse/vec.rs
It seems to have been decided previously that the program should simply panic when invalid arguments are given during vector / matrix construction, since it's the caller's responsibility to ensure correctness. However, the direct caller might not have constructed the input themselves, and could also have received the input from elsewhere (e.g. user input, untrusted file, etc.). To prevent panics, the caller must manually validate the input, which is not completely trivial, especially for matrix construction. By providing the `try_` constructors, the caller can choose to reuse the validation logic in the sprs library, and gracefully recover from invalid inputs.
Let me know what you think :)
> Add `try_` constructors for owning vector & matrix

- .travis.yml
- src/indexing.rs
Running `cargo test --release` on my local machine, I realized some tests failed because the overflow checks are now panicking in the release build as well. This was not caught by the CI because it runs only in debug mode.
Therefore I'm adding the tests in the release mode to the CI, and fixing the overflow tests to also expect panic in release builds.
> Exercise overflow checks in all build configurations

- src/sparse/triplet.rs
- src/sparse/triplet_iter.rs
The invariant that, after suppressing duplicates, `slot` should be equal to the number of nonzeros
was not respected with an empty input.
Fixes #170
> Fix triplet to CSR conversion with empty input.

- src/sparse/triplet.rs
- src/sparse/triplet_iter.rs
The previous fix was not working for matrice ending with empty lines/columns.
This commit fixes this issue and adds a related test.
> Fix triplet to csr conversion for input ending with empty lines

- src/sparse/triplet.rs
- src/sparse/triplet_iter.rs
The previous fix was incomplete due to a bogus test. This commit adds a
more comprehensive test that should cover all edge cases.
Fixes #170 (again...).
> Fix handling of empty lines in triplet to CSR/CSC

- .travis.yml
- Cargo.toml
- src/lib.rs
- src/sparse/binop.rs
- src/sparse/csmat.rs
- src/sparse/mod.rs
- tests/bincode_ser.rs
Currently serde (and serde_derive) are mandatory dependencies, while some users may not need serialization capability. They pull in additional 11 dependencies (e.g. while building sprs), which is non negligible particularly for downstream projects.
I think it would be better to make them optional, as for instance ndarray is doing.
Currently enabling serialization for sprs could be done with,
```
cargo build --features=serde,serde_derive
```
Alternatively those could be put behind a single feature flag (e.g. `serialization` or `serde-1`). 
It is also possible to add them to the list of default features, though I think consistency with `ndarray` on this would be preferable (i.e. not having them enabled by default).
> Make serde and serde_derive dependencies optional 

- README.rst
- src/sparse/binop.rs
Makes it a bit easier to know which is currently the latest version.
Edit: the rendered version is [here](https://github.com/rth/sprs/blob/crates.io-badge/README.rst).
> DOC Add crates.io badge to the readme

- Cargo.toml
- src/sparse/binop.rs
As far as I can tell, sprs builds fine and tests pass with ndarray 0.13. 
So I imagine the supported range of versions could be extended (otherwise I can't use it alongside ndarray 0.13).
Not sure if it's necessary to test it in CI (or how to do that).
> Extend supported ndarray version to 0.13

- examples/fill_in_reduction.rs
- src/sparse/linalg/mod.rs
- src/sparse/linalg/ordering.rs
See also #185 .
This changes the Cuthill-McKee algorithm implemented here to the reverse Cuthill-McKee algorithm. Starting vertices are choosen by a George-Liu pseudoperipheral vertex finder.
I have added two more test cases and verified the correctness of the exisiting one w.r.t. the new algorithm.
I did try to write in the style of the library, however I might not always have got it right when to use `.index()`, when to call `.unwrap()` vs `.expect()`, and so on. Feel free to change these details, as well as remove unneccesary comments or line breaks. I just can't get enough of those.
As benchmark possibilities are scarce, I did not optimize anything to aggressively. I really believe this crate should come with some sparse matrix collection as well as random matrices to benchmark …
> Implementation reverse Cuthill-McKee

- .travis.yml
- .travis_nightly
- Cargo.toml
- sprs-benches/.cargo/config
- sprs-benches/.gitignore
- sprs-benches/Cargo.toml
- sprs-benches/README.md
- sprs-benches/build.rs
- sprs-benches/src/eigen.cpp
- sprs-benches/src/main.rs
As noted in #188, benchamrks were needed to be able to monitor the performance of sparse matrix products.
In this PR, I implemented benchmarks of the old and new (SMMP) implementation of product in sprs, scipy's matrix product, and also the product for the C++ library eigen.
There are benchmarks inspecting the influence of the matrices shape on the performance, with the number of non zeros growing as the number of rows:
The quadratic performance of the old product implementation can clearly be seen. It's also possible to observe that eigen has a lower performance than scipy and sprs, and I suspect this is because their sparse matrix format is an extension of CSR that reserves some space to be able to more efficiently insert new elements in the matrix. Maintaining this possibility must …
> Sparse product benches

- src/lib.rs
It seems some structures are not exported in the docs, which makes it hard to understand how they work, and which traits they implement.
It would be nice if such items were exported automatically, which they are if `pub mod sparse` is added to the topleve. But adding `pub mod sparse` will add `Re-exports` to all the type definitions on the toppage, which makes it difficult getting an overview. Is there a better way of handling this?
> export iterators

- Cargo.toml
- sprs-benches/.cargo/config
- sprs-benches/src/main.rs
- src/indexing.rs
- src/sparse/csmat.rs
- src/sparse/smmp.rs
- src/sparse/vec.rs
This pull request improves the performance of the sparse matrix product by taking advantage of multiple cores, thanks to rayon. Here are benchmark results demonstrating the improvements (benchmarked on a AMD Ryzen 7 3700X 8-Core Processor this time):
Here's a description of the entries:
- the red line corresponds to the SMMP algorithm as implemented in #187.
- the pink line (boolvec 1T) is a micro-optimization of the SMMP algorithm, using a `Vec<bool>` in the symbolic part of the algorithm to check if a column has been seen, which is more cache friendly than the index based "linked list" in the original SMMP algorithm
- boolvec 2T and 4T are the same as boolvec 1T, but with the workloads for the symbolic and numeric parts divided on respectively 2 and 4 threads.
- boolvec auto dynamically …
> Parallel smmp

- sprs-benches/src/main.rs
- src/sparse/prod.rs
- src/sparse/smmp.rs
Recent PRs have introduced a more efficient matrix-matrix product. There is no benefit to keeping the old implementation around. Since the old product was a public API, this is a breaking change and will require bumping `sprs` version to 0.8.
> Remove old product implementation

- .github/workflows/ci.yml
- .travis_nightly
- Cargo.toml
- sprs-benches/Cargo.toml
- sprs-ldl/Cargo.toml
- sprs-ldl/src/lib.rs
- sprs-rand/Cargo.toml
- src/lib.rs
- src/sparse/csmat.rs
- suitesparse_bindings/sprs_suitesparse_ldl/Cargo.toml
- suitesparse_bindings/sprs_suitesparse_ldl/src/lib.rs
This pull request introduces a more ergonomic API to the LDL factorization algorithm, which makes it easy to compute a factorization yet allows customization of some options, such as disabling symmetry check or choosing a method to get a good fill-in reducing permutation.
This should help investigate #199.
> Enhance ldl API

- src/lib.rs
- src/sparse/linalg/ordering.rs
- src/sparse/permutation.rs
Add functions to check permutation validity, and check the validity of permutations when they are created from vectors of indices.
> Permutation validity

- sprs-ldl/src/lib.rs
I've investigated performance differences between `sprs-ldl` and `sprs-suitesparse-ldl`. As it turns out, the bindings over the C library were faster, mostly because bounds checking had a high impact in a tight loop.
Fortunately, using an iterator could remove one of the offending bound checks, and I've been able to prove the other bounds check unnecessary regardless of the inputs, which means some unsafe indexing can be used.
This should help #199.
> Faster ldl decomposition

- .github/workflows/ci.yml
- Cargo.toml
- src/sparse/smmp.rs
As mentioned in #208 rayon will panic when creating a threadpool on targets which do not have threads. This PR puts `rayon` and `num_cpus` behind the feature flag `multi_thread` (suggestions for name?), but otherwise follows exactly the same code path as the `Fixed(1)` case.
Fixes #208
> Optional rayon

- src/lib.rs
- src/sparse.rs
- src/sparse/kronecker.rs
This is a slightly modified version of the one in #209, which uses some symmetries for the `CSC^2` -> `CSR^2` case.
The incompatible storage case is now handled by converting the second matrix to the opposite storage. This might not be the most efficient, but the performance should be predictable in this case.
Closes #209
> Add Kronecker product

- .github/workflows/ci.yml
- Cargo.toml
- src/lib.rs
- src/sparse/csmat.rs
- src/sparse/vec.rs
This implements `approx` for sparse vectors and matrices. This can be very useful for comparing matrices, as the  `PartialEq` checks for structural equality, and the approx traits "ignore" the storage type.
Fixes #197
> impl approx

- src/sparse/vec.rs
Adding the `#[inline]` attribute to the indexing operators got a speedup of 15-30% on `mul_acc_mat_vec_csr` for some matrices. The benchmarks in this library does not gain or lose anything from this change.
Further observations: Changing to unsafe access in `mul_acc_mat_vec_csr` does not modify the performance characteristics compared to the safe version.
> Add #[inline] to indexing

- Cargo.toml
- src/sparse.rs
Just improved the utils::sort_indices_data_slices a bit, while I'm using this crate (very nice crate!)
The change includes 1) the removal of the explicit bound check using iterators, and 2) a quick test to verify my changes.
> make some small improvements in the utils:sort_indices_data_slices

- src/io.rs
- src/lib.rs
- src/sparse/csmat.rs
- src/sparse/permutation.rs
- src/sparse/prod.rs
- src/sparse/smmp.rs
- src/sparse/special_mats.rs
There is a bug in `mul_acc_mat_vec_csr` and `mul_acc_mat_vec_csc`. Basically, the output `res_vec` needs to be set to zero before accumulating values in the matrix vector multiplication.
I also btw did some small tweaks following the suggestions from `cargo clippy`
> fixed a bug in mul_acc_mat_vec_csr and mul_acc_mat_vec_csc

- .github/workflows/ci.yml
- README.md
- src/sparse/csmat.rs
- suitesparse_bindings/sprs_suitesparse_camd/src/lib.rs
As evidenced by #222, it's important to explicitly state which rust version we require as a minimum, and to test for it in CI to ensure it does not change too fast.
> Check for Minimum Supported Rust Version

- src/lib.rs
- src/sparse/csmat.rs
- src/sparse/vec.rs
This implements `MulAssign` and `DivAssign` for matrices and vectors.
The `MulAssign` could be expressed as `scale`, but it's nice to have multiple options. `DivAssign` might be less efficient than doing inversion of `rhs` then scaling, altough some cases migh benefit from direct division.
The `impl`s are quite broad, but this should not be a problem as sparse inplace vector-vector multiplication is probably not very efficient.
(The first commit removes a deprecated type)
> Implement MulAssign and DivAssign

- src/array_backend.rs
- src/sparse/csmat.rs
Multiplication of `(CSC, CSR)` matrices would lead to a crash for valid matrices. `(CSC, CSR)` should instead copy the format of `(CSC, CSC)` with `rhs` transposed.
Ref #99
> Fix (CSC, CSR) multiplication

- Cargo.toml
- benches/sorting.rs
- src/sparse.rs
- src/sparse/csmat.rs
- src/sparse/vec.rs
The current behaviour is to always copy the indices and data to a new vector, sort it, then copy back. This PR instead checks if the vector/matrix needs sorting before doing this.
This PR does introduce a regression in the the `csvec_additive_inverse` and `csvec_neg` benchmarks, which is because of `malloc` being called more often for some reason. I think we are dealing with a (not so?) clever optimiser, and this should not be a regresson in code used elsewhere.
The additional commit adds the Copy clone to `derive` which should produce the same code, and adds the `must_use` attribute so one does not accidentally drop the result of a(n expensive) calculation.
> Check if needs to be sorted

- .github/workflows/ci.yml
- .gitmodules
- Cargo.toml
- sprs-benches/Cargo.toml
- suitesparse_bindings/sprs_suitesparse_ldl/Cargo.toml
- suitesparse_bindings/suitesparse-src/Cargo.toml
- suitesparse_bindings/suitesparse-src/README.md
- suitesparse_bindings/suitesparse-src/build.rs
- suitesparse_bindings/suitesparse-src/src/lib.rs
- suitesparse_bindings/suitesparse_camd_sys/Cargo.toml
- suitesparse_bindings/suitesparse_camd_sys/build.rs
- suitesparse_bindings/suitesparse_camd_sys/src/lib.rs
- suitesparse_bindings/suitesparse_ldl_sys/Cargo.toml
- suitesparse_bindings/suitesparse_ldl_sys/README.md
- suitesparse_bindings/suitesparse_ldl_sys/README.rst
- suitesparse_bindings/suitesparse_ldl_sys/build.rs
- suitesparse_bindings/suitesparse_ldl_sys/src/lib.rs
This adds feature flags for `suitesparse_ldl_sys` and `suitesparse_camd_sys` to build `SuiteSparse` from source and statically link it. This should be easily extendable to more components later on if more parts are wanted. We might want to add this feature flag to the `sprs_suitesparse` packages.
The build script for `SuiteSparse` reimplements the `Makefile`s, as these were hard to reuse, I've added CI which should ensure we won't break this.
The targeted version of `SuiteSparse` is v5.8.1, and parts of this will be uploaded to `crates.io`. This should be compatible with the licenses of the included components.
> Build suitesparse from source

- src/sparse.rs
- src/sparse/csmat.rs
- src/sparse/vec.rs
This is a first step in disallowing invalid structures from being created, to uphold the guarantees of sortedness of the structures.
This limits the surface where non-sortedness could appear by calling `new_trusted`. We could add debug assertations to `new_trusted` if we are paranoid.
Methods to test if invariants are upheld has been moved to the `utils` module. They could be useful for library users, and could be made public.
> Checked constructors for CsVec and CsMat

- src/sparse.rs
- src/sparse/csmat.rs
It would be convenient for the sparse data structures in sprs to implement `Hash`, and deriving it should be fine.
This PR also adds `Eq` to `CsVecBase`.
> Derive Hash on sparse storage containers

- src/sparse/csmat.rs
`u8`/`i8`/`u16`/`i16` was not handled with the macro, and was not consistent with the other primitives
> Add scalar multiplication for primitive types

- src/sparse/csmat.rs
Create the correct shape of the view returned from `middle_outer_views` when `self` is a `CSC`
> Fix shape-bug for CSC in middle_outer_views

- src/sparse/csmat.rs
There's probably a possibility to have separate nnz implementations, but my rust knowledge is not up to the task. This might not be a hot method, so probably not a big problem.
> Fix nnz for partial views + add test to expose

- src/sparse.rs
- src/sparse/indptr.rs
This does not uphold the invariants of `IndPtr`, but this would be easier to introduce in #237
Flattening `IndPtr` gives us backwards compatibility.
> Serde deserialization for IndPtr

- src/sparse/csmat.rs
- src/sparse/indptr.rs
- src/sparse/smmp.rs
- src/sparse/triplet.rs
Advantage is in comparing a slice and an `IndPtr`, without the drawbacks of a `Deref` on `IndPtr` which would ignore the properness
> add a PartialEq for indptr and slices

- sprs-benches/src/main.rs
- sprs-ldl/src/lib.rs
- src/lib.rs
- src/sparse.rs
- src/sparse/binop.rs
- src/sparse/csmat.rs
- src/sparse/indptr.rs
- src/sparse/permutation.rs
- src/sparse/smmp.rs
- src/sparse/triplet.rs
- src/sparse/triplet_iter.rs
- src/sparse/vec.rs
- suitesparse_bindings/sprs_suitesparse_camd/src/lib.rs
- suitesparse_bindings/sprs_suitesparse_ldl/src/lib.rs
This is a refactoring that should fix #244. This is very much WIP, but the basic test suite is passing. @mulimoen I'd be very interested in your feedback.
This introduces lots of breaking changes, for instance lots of iterators are now using an `impl Iterator` pattern instead of an explicit type.
There are still a few rough edges, which may not be addressed in this PR but should be addressed before 0.10 is released:
- `middle_outer_views` is cumbersome to use, it probably should take a start and end parameter (or a range) to be more convenient and less error prone.
- the `IndPtr` type is not used to build owned indptr types, but it could be interesting to use it to enforce good patterns. As it would not be practical to have runtime checks, this would be a crate-only API
- smmp was quite …
> Refactor to allow partial views

- Cargo.toml
- sprs-ldl/Cargo.toml
- src/io.rs
- suitesparse_bindings/sprs_suitesparse_ldl/Cargo.toml
This ensures all dependencies are the same version
> use same version of dependencies

- .github/workflows/ci.yml
- sprs-benches/build.rs
- sprs-benches/src/main.rs
- sprs-ldl/src/lib.rs
- sprs-rand/src/lib.rs
- src/indexing.rs
- src/io.rs
- src/lib.rs
- src/sparse.rs
- src/sparse/binop.rs
- src/sparse/compressed.rs
- src/sparse/construct.rs
- src/sparse/csmat.rs
- src/sparse/linalg/ordering.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/permutation.rs
- src/sparse/smmp.rs
- src/sparse/triplet.rs
- src/sparse/triplet_iter.rs
- src/sparse/vec.rs
- src/stack.rs
- suitesparse_bindings/suitesparse-src/src/lib.rs
- suitesparse_bindings/suitesparse_camd_sys/src/lib.rs
This is just a collection of clippy lints which are not enabled by default, but improves code consistency slightly. The documentation should be a bit prettier now with all `doc_markdown` lints fixed.
> Some pedantic clippy lints

- src/sparse.rs
- src/sparse/binop.rs
- src/sparse/csmat.rs
The `binop` methods was determining whether to transpose or not based on `is_standard_layout`. These checks are replaced with fastest and slowest axis instead, closer matching the semantics wanted. This makes matrix slices cheaper to work with during addition and multiplication as we don't have to transpose a `CSR` into `CSC` unnecessarily
> Slice friendly binop

- src/sparse/csmat.rs
A method to add fetching the diagonal of a matrix. 
I'm quite new to Rust, so I'm not sure if this useful. It's intended to spark a discussion around the implementation. I really wanted the a `diag_view` method, but I'm not sure how to implement it, so ideas are welcome.
> Add  `diag` method to CsMatBase

- Guidelines.rst
- src/lib.rs
- src/range.rs
- src/sparse.rs
- src/sparse/csmat.rs
- src/sparse/indptr.rs
- src/sparse/slicing.rs
- src/sparse/smmp.rs
- tests/slicing.rs
As mentionned in #250, the slicing of middle matrices along the outer dimension is quite cumbersome to use, which is particularly visible in the matrix product implementation in `smmp.rs`. This PR tries to propose a more ergonomic API.
> More ergonomic slicing

- .github/workflows/ci.yml
- src/lib.rs
If we have to add some unsafe code we should ensure we don't do it wildly wrong. I suggest adding `miri` to the CI which could catch some undefined behaviour.
The `io` module can not be tested with `miri` as file operations are not supported
> add miri workflow

- sprs-ldl/src/lib.rs
- src/errors.rs
- src/lib.rs
- src/sparse.rs
- src/sparse/binop.rs
- src/sparse/csmat.rs
- src/sparse/indptr.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/serde_traits.rs
- src/sparse/vec.rs
- suitesparse_bindings/sprs_suitesparse_camd/src/lib.rs
- suitesparse_bindings/sprs_suitesparse_ldl/src/lib.rs
Recent work has made the structural constraints of sparse matrices and vectors clearer, making it clear that there can be a single enum discriminating all possible structural errors. Having linalg errors in the same error type was clumsy: structural errors happen when creating a matrix, while linalg errors happen much later, when solving systems or performing other linear algebra operations. Therefore, by splitting the types, it should be easier to react to both kinds of errors.
Since the linalg part of this crate is still small, it's expected that I'm missing possible errors, which is why the error type is a non
exhaustive enum.
Additionaly, I took this refactoring as an opportunity to fix #255, using the same pattern used by the `CsMatBase` and `CsVecBase` constructors to return the …
> Split the error type between structural and linalg errors

- .github/workflows/ci.yml
- src/io.rs
- src/lib.rs
- src/sparse/csmat.rs
- src/sparse/triplet.rs
- src/sparse/triplet_iter.rs
It would be good to convert triplet matrix to a cs with chosen `Iptr` type.
There might be a way to let `Iptr = I` as default?
> Triplet matrix conversion to compressed storage with given Iptr

- src/sparse/csmat.rs
- src/sparse/smmp.rs
This makes a friendlier API, and will allow relying on CsMat invariants
for performance later on (eg by removing some bounds checking). The code
is also a lot more readable now.
Fixes #254.
> Use CsMatView as input to smmp functions

- benches/sorting.rs
- src/sparse/csmat.rs
- src/sparse/serde_traits.rs
- src/sparse/vec.rs
This is the vector analouge to #274 
The new API consists of
* `new`: Constructors which panics on failure
* `try_new`: Returns all buffers and the error
* `new_sorted`: A constructors that may sort the indices and data
* `new_unchecked`: Does zero checking of constraints
Internal:
* `new_trusted`: The internal version of `new_unchecked`
A bunch of the other constructors were removed. These can be expressed in some form of the above. The `unsafe` view constructors are removed in preference to `new_unchecked`, where the caller must ensure valid lifetimes
Fixes #273
> CsVec constructors

- sprs-ldl/src/lib.rs
- src/dense_vector.rs
- src/lib.rs
- src/sparse/linalg.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/permutation.rs
- src/sparse/prod.rs
- src/sparse/vec.rs
Lots of APIs were using slices as their input, particularly when using
output buffers. However, this was not a good fit for linear algebra,
since consumers of the APIs are more likely to be using eg an array from
ndarray.
Here we extend the `DenseVector` trait with a mutable version to be able
to use it on output parameters. Since these are sealed traits we should
be able to add unsafe indexing if necessary without a breaking change.
It should also be possible to support eg nalgebra in the future without
too much trouble.
This should improve the situation discussed in #93, though it's
probably not done yet.
> Draft: Support generic dense vectors in more APIs

- sprs-ldl/src/lib.rs
- src/io.rs
- src/lib.rs
- src/mul_acc.rs
- src/sparse.rs
- src/sparse/binop.rs
- src/sparse/csmat.rs
- src/sparse/kronecker.rs
- src/sparse/linalg.rs
- src/sparse/linalg/trisolve.rs
- src/sparse/permutation.rs
- src/sparse/prod.rs
- src/sparse/smmp.rs
- src/sparse/vec.rs
- src/stack.rs
- tests/block_matrix.rs
This pull request removes the `Copy` bound from most functions and methods, fixing #121.
While removing the bound, I tried to ensure there were not too many unnecessary calls to `Clone`, with the idea that this should enable storing more complex data as our scalar type (such as big ints, or heap-allocated matrices to have sparse by blocks matrices) while remaining performant.
The main way the unnecessary clones have been removed is through the introduction of the `MulAcc` trait, which represents the fundamental operation for matrix products. Since it takes its arguments by reference, it should be possible to implement this trait without unnecessary allocations for heab-based scalar types. For convenience, this trait is automatically implemented for all `Copy` types that also implement …
> Relax copy bound

- changelog.rst
- src/mul_acc.rs
- src/sparse/prod.rs
Partial implementation of #283
> fully generic MulAcc<A,B> - groundwork for Fully Generic Matrix/Vector element, Product and Accumulator Types - 

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- changelog.rst
- examples/heat.rs
- sprs-ldl/Cargo.toml
`ndarray` had a version bump, but we are still compatible with all versions. This is not a breaking change.
> Bump ndarray

- Cargo.toml
- examples/fill_in_reduction.rs
- src/sparse/binop.rs
- src/sparse/csmat.rs
- src/sparse/vec.rs
- tests/asymmetric_operands.rs
Alters the existing pointwise addition, subtraction, and multiplication binary operators so that they allow for different left-hand and right-hand side operands.
Note that in some cases this can lead to minor backwards incompatibilities due to the need to specify the type of one operand as it cannot be inferred automatically (e.g. when using an "eye" matrix). Please consider bumping the minor version number if merging.
> Add asymmetric operands to pointwise binary ops

- sprs/src/io.rs
Made a tiny refactor, in order to support I/O to gzipped matrixmarket files.
Also changed trait bound to relax ?Sized on BufRead/Write, for
same end-goal.
> minor refactor, to support reading/writing to/from gzip files

- sprs/src/dense_vector.rs
- sprs/src/sparse/prod.rs
I've added some code to tests the DenseVector trait.
I used [tarpaulin](https://github.com/xd009642/tarpaulin) to evaluate the coverage improvement of the dense_vector.rs file: from 35% to 64%.
The tests are pretty simple. If you agree, I'd like to write some more unit tests to get confident with the library code and after that contributing on the algorithms.
I've a C++ dev background, and I've recently started learning Rust, so feel free to highlight any mistakes a did.
> Add unit tests for DenseVector

- sprs/data/matrix_market/pattern.mm
- sprs/src/io.rs
- sprs/src/num_kinds.rs
- sprs/src/num_matrixmarket.rs
- sprs/src/sparse/triplet.rs
- sprs/src/sparse/triplet_iter.rs
the [pattern]( https://math.nist.gov/MatrixMarket/formats.html#MMformat) type is simply a zero-sized structure. update the io module to support:
1. read an MTX file with pattern type
2. read a normal non-pattern MTX file as a pattern-type MTX, ignore the data filed. #318
> update pattern type

- sprs/src/sparse/binop.rs
- sprs/src/sparse/vec.rs
Following #319, I have relaxed the trait requirements for `Add`, `Sub` etc for `CsVec`, so that in particular we can add and subtract vectors with scalar types that does not necessarily implement the `num_traits::Num` trait.
> relax trait requirements for binary operations.

- sprs/src/mul_acc.rs
- sprs/src/sparse/csmat.rs
Modified the default implementation of `MulAcc`, so that the default implementation applies to scalar types that does not necessary implement `Copy` and `num_traits::MulAdd`. In particular, this modification enables [`BigInt`](https://github.com/rust-num/num-bigint) and [`Rational`](https://github.com/rust-num/num-rational) types applicable. 
Follows discussion from #323.
> Modifying the default implementation for MulAcc.

- sprs/src/sparse/csmat.rs
We use sprs for large sparse matrices with dims > 250,000,000. Currently the options to build a matrix requires realizing a `CsVecI` or a dense vector, which is inefficient.
Adding `append_outer_iter` helps with this without adding much code.
Makes e.g. filtering out a component from a large matrix much simpler and efficient.
> Add append_outer_iter

- sprs/src/lib.rs
- sprs/src/sparse/permutation.rs
- suitesparse_bindings/sprs_suitesparse_umfpack/src/lib.rs
* Add private functions `permute_inner` and `permute_outer` that separate the permutation of inner and outer dimensions as found in `transform_mat_papt`
* Add public functions `permute_rows` and `permute_cols` that select either `permute_inner` or `permute_outer` depending on storage
* Add public function `transform_mat_paq` that mirrors `transform_mat_papt` but allows different permutations for rows and cols and allows nonsquare matrices
* Use `transform_mat_paq` to test umfpack bindings' numeric factorization outputs
* Incidentally macroize umfpack tests to reduce boilerplate overhead
> Add more permutation functionality

- sprs/src/sparse/linalg.rs
- sprs/src/sparse/linalg/bicgstab.rs
Some thoughts about this implementation -
Pros
* It runs and is even fairly correct and a bit documented
* Implemented on f32 and f64 with generic indices
Cons
* Doesn't represent any particular reusable abstract pattern of iterative solver interface, and only makes a little progress toward the goals of #339 
* Solver call signature requires the turbof***
* I haven't found any way around this - even when it's obvious from the inputs and outputs which variant should be selected, it still fails to select the correct variant without explicit type annotation
* Macros make things worse for the users in terms of readability, understanding errors, etc
* Not fully generic on value type
* Not generic on sparse vs. dense RHS and initial guess
* Can't be implemented directly on Complex<T> types
* …
> Implement BiCGSTAB

- sprs-ldl/Cargo.toml
- sprs/Cargo.toml
- sprs/benches/sparse_dense_products.rs
- sprs/examples/heat.rs
- sprs/src/sparse/csmat.rs
It will build & tests pass with either 0.15 or 0.16.  We'd like to upgrade to ndarray 0.16.
> chore: widen ndarray version

- sprs/src/sparse/csmat.rs
- sprs/tests/gh374.rs
> Fix Index conversion turning OOB
