.gitignore, src/sparse/binop.rs, src/sparse/compressed.rs, src/sparse/construct.rs, src/sparse/csmat.rs, src/sparse/prod.rs, src/sparse/vec.rs, src/test_data.py, src/test_data.rs
Expose common algebraic operations on matrices and vectors via the operators.
Closes #1.
=> Operation traits

.travis.yml, README.rst, src/errors.rs, src/lib.rs, src/sparse/binop.rs, src/sparse/csmat.rs, src/sparse/prod.rs, src/sparse/vec.rs
=> Doc examples

src/sparse/binop.rs, src/sparse/compressed.rs, src/sparse/csmat.rs, src/sparse/linalg/cholesky.rs, src/sparse/prod.rs, src/sparse/symmetric.rs, src/sparse/vec.rs, src/test_data.rs
CsMat is now generic over all of its kinds of storages, be it indptr's, indices', or data's.
=> Generic storage

Cargo.toml, src/sparse/compressed.rs
@dylanede, would this be ok for your abstraction needs?
=> add a trait to abstract over CsVec, see #42

src/sparse/vec.rs
Enable dot product to work with dense types such as std vectors and slices, and ndarray's 1D arrays.
Fixes #60.
=> Sparse dot product enhancement

src/sparse/binop.rs, src/sparse/csmat.rs, src/sparse/mod.rs, src/sparse/to_dense.rs
=> Sparse to dense conversion

examples/heat.rs
Add an example for using sprs to solve a classical sparse problem: diffusion.
Fixes #86.
=> Heat diff example

src/sparse/csmat.rs, src/sparse/vec.rs
=> implement matrix cloning with index type conversion

.travis.yml, sprs-ldl/src/lib.rs, src/lib.rs, src/sparse/csmat.rs, src/sparse/permutation.rs, src/sparse/vec.rs, suitesparse_bindings/sprs_suitesparse_ldl/.gitignore, suitesparse_bindings/sprs_suitesparse_ldl/Cargo.toml, suitesparse_bindings/sprs_suitesparse_ldl/src/lib.rs, suitesparse_bindings/suitesparse_ldl_sys/.gitignore, suitesparse_bindings/suitesparse_ldl_sys/Cargo.toml, suitesparse_bindings/suitesparse_ldl_sys/README.rst, suitesparse_bindings/suitesparse_ldl_sys/src/lib.rs
LDL is a simple sparse Cholesky factorization package. A pure rust re-implementation is available in the sprs-ldl crate, but binding to the original implementation will prove useful for assessing the correctness and performance of the rust implementation. This also provides an example for binding more suitesparse packages.
One step for #21.
=> Bind suitesparse's LDL package

src/sparse/to_dense.rs
Fixes small typo during dimension checking.
=> Fix to_dense for non square matrices

Cargo.toml, benches/sparse_dense_products.rs, src/sparse/csmat.rs, src/sparse/mod.rs, src/sparse/prod.rs, src/sparse/vec.rs
Fixes #125. See the issue for details of the investigation. @usamec I hope this addresses your pain points.
=> Improve performance of sparse-dense operations

src/sparse/csmat.rs
See #129 for the relevant bug report.
=> fix iteration bug with multiple adjacent empty rows

suitesparse_bindings/sprs_suitesparse_ldl/src/lib.rs
Fixes `cargo fmt --check` error encountered in PR #135
=> run `cargo fmt` with Rust 1.30 (update from 1.29)

Cargo.toml, changelog.rst
Just a heads-up that I'm going to release the latest improvements on crates.io as a version 0.6.3.
I want to thank again @pmarks @toastronics @tomtung @rth for your contributions.
=> Version 0.6.3

src/sparse/prod.rs
Using binary search changes the time complexity from O(M+N) to O(MlogN), where M and N are the number of non-zero entries in each vector. This results in a significant speed-up when N>>M.
For more context, I used it here at https://github.com/tomtung/parabel-rs/commit/604970116c69900c12ce12161ea9b3d827961684 where we are doing predictions using linear classifiers trained on sparse vectors with millions of dimensions. The feature vector for a given example is usually sparse with relatively few (e.g. tens of) non-zero entries. The weight vector of a classifier is also quite sparse but still contain many non-zero entries (e.g. 5% of 1 million is still 50,000). As a result, computing the dot product between the two in O(M+N) time is extremely slow.
=> Support computing sparse vector dot product using binary search

Cargo.toml, changelog.rst
Publish the enhancements to sparse/sparse vector dot products to crates.io
Thanks @tomtung for the report and fixes!
=> version 0.6.4

src/sparse/vec.rs
Mostly just porting the logic from [NumPy](https://github.com/numpy/numpy/blob/v1.16.1/numpy/linalg/linalg.py#L2467-L2491) and [Eigen](https://github.com/eigenteam/eigen-git-mirror/blob/3.3.7/Eigen/src/Core/Dot.h#L203-L246).
=> Support computing vector norms

sprs-ldl/Cargo.toml, sprs-ldl/src/lib.rs, suitesparse_bindings/sprs_suitesparse_ldl/Cargo.toml, suitesparse_bindings/sprs_suitesparse_ldl/src/lib.rs, suitesparse_bindings/suitesparse_ldl_sys/Cargo.toml, suitesparse_bindings/suitesparse_ldl_sys/src/lib.rs
=> [ldl] return result to notify failure of LDL decomposition

src/sparse/csmat.rs
=> implement Dot from linalg

src/io/mod.rs
required for reading from compressed files or the network.
=> add a method for reading MatrixMarket from an arbitrary io::BufRead

src/sparse/mod.rs
=> implement Eq for CsMatBase

src/sparse/csmat.rs
allow CsMat::map to return a new type
=> allow CsMat::map to return a new type

src/sparse/vec.rs
Hey, I've noticed that I can't subtract CsVecs with custom index types. This is probably just an omission.
=> add missing `I` param to the Sub impl for CsVecBase

Cargo.toml, sprs-rand/Cargo.toml, sprs-rand/src/lib.rs, src/sparse/csmat.rs
This pull request adds the ability to generate a sparse matrix with a random structure and random values. This will be helpful for #188.
=> Random sparse matrix generation

src/sparse/csmat.rs
Hey @vbarrielle,
As in #190, here is an implementation of 'to_inner_onehot'.
I thought about writing 'to_row_onehot' and 'to_column_onehot', because users would probably want to onehot along a specific direction, but settled on adding 'into_csc' and 'into_csr', which cheaply return self if the CSC/CSR compression type is correct.  They can only be called on an owned CsMatBase with Vec storage, as the return type between the branches needs to be equal. 
Users can chain them: `mat.into_csr().to_inner_onehot()`
Also, the where bound could be lowered to `N: Num` if to_inner_onehot panicked on NaNs.  Right now it requires `N: Float` so that NaNs can be filtered out before the max_by.
Let me know if you have any comments.
=> Add to_inner_onehot, into_csc, and into_csr

Cargo.toml, benches/sparse_dense_products.rs, benches/suite.rs, examples/fill_in_reduction.rs, src/lib.rs, src/sparse/csmat.rs, src/sparse/linalg/ordering.rs, src/sparse/vec.rs, src/sparse/visu.rs
When initially stumbling upon this crate I was a bit confused on how to create a matrix by using indices. I've added an example of how to create a matrix using the `TriMat` structure, which one can later convert to a compressed format.
In addition I updated the dependencies, fixed two doc-links, and some clippy lints.
=> Documentation and other small updates

.github/workflows/ci.yml, sprs-benches/src/main.rs, sprs-ldl/src/lib.rs, src/lib.rs
As suggested during review of #218. Fixes #219.
=> Deny warnings on ci

src/sparse/smmp.rs
nb_threads should never be set higher than l_rows, so this PR sets it to `std::cmp::min(l_rows, {...})`
fixes #234
=> add safeguard for nb_threads being set too high

src/sparse/smmp.rs
=> Fix matrix product with zero rows

src/sparse/csmat.rs
This `CsMatBase` is actually a `CsMatViewI` in disguise
=> type can be expressed as view

sprs-tests/tests/tests.rs, src/sparse.rs, src/sparse/serde_traits.rs, tests/bincode_ser.rs
As noted in #256, there was a failure when serializing with bincode. This PR should fix it by implementing `Serialize` manually. See https://github.com/servo/bincode/issues/245 for the source of the issue.
=> Fix serde serialization

src/sparse/csmat.rs, tests/outer_iterator.rs
Test and fix for #261 
Introduces unsafe code, please review carefully
=> Fix outer_iterator_mut DoubleEnded iterator

src/sparse/csmat.rs
These are iterating counter-parts to `diag`.
The mutable iterator contains `unsafe`, please check if I have missed anything regarding safety for this.
=> add iterators for the diagonal

src/sparse/to_dense.rs, src/sparse/vec.rs
Add method `CsVecBase::to_dense()`
=> Add CsVecBase::to_dense()

Cargo.toml, sprs-ldl/Cargo.toml
=> Increase supported versions of ndarray up to 0.14

Cargo.toml, changelog.rst, sprs-benches/Cargo.toml, sprs-ldl/Cargo.toml, sprs-rand/Cargo.toml, suitesparse_bindings/sprs_suitesparse_camd/Cargo.toml, suitesparse_bindings/sprs_suitesparse_ldl/Cargo.toml
I think the round of refactoring for 0.10 is complete now, I can't think of some more breaking changes we might want to add. So I think I'm going to publish 0.10 soon. @mulimoen do you see something I could have forgotten?
=> Version 0.10

.github/workflows/ci.yml, sprs-benches/Cargo.toml, sprs-benches/src/main.rs
I'm not sure if this is done correctly, but it seems to work (passes cargo test, cargo bench).
It seems the way a method gets called has changed.
=> minor code fix to upgrade pyo3 to 0.16.5

sprs/src/stack.rs
I've added some unit tests for the DStack (stack.rs).
The coverage is improved from 65% to 100%. I used [tarpaulin](https://github.com/xd009642/tarpaulin) to evaluate the coverage.
=> add unit tests for DStack

sprs-rand/LICENSE-APACHE, sprs-rand/LICENSE-MIT, sprs/LICENSE-APACHE, sprs/LICENSE-MIT
Hey, thanks for this library!
This PR symlinks the license files so they're included in the published crates (like with sprs 0.11.0).
=> Include license files in published crates

.github/workflows/ci.yml, Cargo.toml, sprs-ldl/src/lib.rs, sprs/src/indexing.rs, sprs/src/sparse/compressed.rs, sprs/src/sparse/csmat.rs, sprs/src/sparse/linalg.rs, sprs/src/sparse/linalg/etree.rs, sprs/src/sparse/prod.rs, sprs/src/sparse/special_mats.rs, sprs/src/sparse/to_dense.rs, sprs/src/sparse/triplet.rs
and some CI upgrades of the actions used
=> Fix outer comments
